### ISSUE TITLE
Keyboard will automatically pop up every time when I open the sky app.

### ISSUE THREAD

**Issue by LyndonChin** [domokit/sky_sdk#12]
* Nexus  7
* Android Version 5.1

**Comment by eseidelGoogle** [comment]
I noticed this as well.  I believe this is a regression since the Dart Summit branch was cut.  Possibly as a result of moving the Keyboard service out of sky/services into mojo/services. @jamesr 

Since sky_sdk is a generated repository, we should track this as an issue in the mojo repo:
https://github.com/domokit/mojo/issues/141

Thanks for the report!
